// RDB
const DATABASE = {
  DATABASE_TYPE: 'DATABASE_TYPE',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_USERNAME: 'DATABASE_USERNAME',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_DATABASE: 'DATABASE_DATABASE',
} as const;

// CACHE STORE
const CACHE_STORE = {
  CACHE_STORE_HOST: 'CACHE_STORE_HOST',
  CACHE_STORE_PORT: 'CACHE_STORE_PORT',
} as const;

// JWT
const JWT = {
  JWT_ACCESS_KEY: 'JWT_ACCESS_KEY',
  JWT_REFRESH_KEY: 'JWT_REFRESH_KEY',
} as const;

const EMAIL = {
  EMAIL_SENDER: 'EMAIL_SENDER',
  EMAIL_PASS: 'EMAIL_PASS',
} as const;

// EMAIL

export const ENV_KEY = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  ...DATABASE,
  ...CACHE_STORE,
  ...JWT,
  ...EMAIL,
} as const;
